CREATE TABLE MOVIES_TABLE
(
    ID NUMBER(10) PRIMARY KEY NOT NULL,
    PATH VARCHAR2(255),
    CATEGORY VARCHAR2(255),
    MODIFIEDDATE TIMESTAMP(6),
    NAME VARCHAR2(255),
    FILESIZE NUMBER(19)
);
CREATE UNIQUE INDEX SYS_C004065 ON MOVIES_TABLE (ID, PATH);