INSERT INTO QUESTION_CATEGORY (ID, CREATION_DATE, MODIFIED_DATE, IS_ACTIVE, IS_LATEST_VERSION, NAME, DESCRIPTION)
VALUES (1, systimestamp, systimestamp, 1, 1, 'QUANTS', 'Quantitative Aptitude');


INSERT INTO QUESTION_CATEGORY (ID, CREATION_DATE, MODIFIED_DATE, IS_ACTIVE, IS_LATEST_VERSION, NAME, DESCRIPTION)
VALUES (2, systimestamp, systimestamp, 1, 1, 'General Intelligence', 'General Intelligence');

INSERT INTO QUESTION_CATEGORY (ID, CREATION_DATE, MODIFIED_DATE, IS_ACTIVE, IS_LATEST_VERSION, NAME, DESCRIPTION)
VALUES (3, systimestamp, systimestamp, 1, 1, 'Comprehension English', 'English');

INSERT INTO QUESTION_CATEGORY (ID, CREATION_DATE, MODIFIED_DATE, IS_ACTIVE, IS_LATEST_VERSION, NAME, DESCRIPTION)
VALUES (4, systimestamp, systimestamp, 1, 1, 'General Awareness', 'General Awareness');

COMMIT;